import { useState, useRef } from 'react';
import './MemeGenerator.css';

// Curated list of funny modern meme backgrounds (Images, GIFs, Videos)
const dynamicMedia = [
  {
    id: 1,
    url: 'https://media.giphy.com/media/LmNwrBhejkK9EFP504/giphy.gif',
    type: 'image',
    name: 'Confused Travolta',
    description: 'Looking around empty rooms'
  },
  {
    id: 2,
    url: 'https://media.giphy.com/media/L0snCScL0LMBor5sE0/giphy.gif',
    type: 'image',
    name: 'Spongebob Burning',
    description: 'Everything is fine'
  },
  {
    id: 3,
    url: 'https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif',
    type: 'image',
    name: 'Homer Backing into Bush',
    description: 'Avoiding awkward situations'
  },
  {
    id: 4,
    url: 'https://i.imgflip.com/4t0m5.jpg',
    type: 'image',
    name: 'Doge',
    description: 'Much funny, very meme'
  },
  {
    id: 5,
    url: 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDExMnRpcm5nY3ZocHZ1NmR5d3NqbzVncmRzbmZpMXJyb2JmbXFkbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l3q2K5jinAlChoCLS/giphy.gif',
    type: 'image',
    name: 'Blinking Guy',
    description: 'Surprised or confused reaction'
  },
  {
    id: 6,
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    type: 'video',
    name: 'Epic Sintel Example',
    description: 'High quality video background'
  }
];

// Brahmanandam GIFs
const brahmanandamGifs = [
  'https://media.tenor.com/_uB5hMmdXJAAAAAC/brahmi-brahmanandam.gif',
  'https://media.tenor.com/aC7UoR_aK3cAAAAC/brahmi-king.gif',
  'https://media.tenor.com/xebx_TXXC70AAAAd/brahmi.gif',
  'https://media.tenor.com/gYcZqYw6h5wAAAAC/brahmi-brahmanandam.gif',
  'https://media.tenor.com/aPz1zX4MowMAAAAC/brahmi-brahmanandam.gif'
];

// Engineering Joke Texts
const engineeringTexts = [
  { top: 'WHEN NPM INSTALL WORKS', bottom: 'WITHOUT ANY ERROR' },
  { top: 'FIXING A BUG AT 3AM', bottom: 'CREATING 10 NEW BUGS' },
  { top: 'CLIENT WANTS IT TOMORROW', bottom: 'I HAVEN\'T STARTED YET' },
  { top: 'CODE COMPILED FIRST TIME', bottom: 'SOMETHING IS WRONG' },
  { top: 'ME EXPLAINING MY CODE', bottom: 'TO THE SENIOR DEVELOPER' }
];

function MemeGenerator() {
  const [topText, setTopText] = useState('');
  const [bottomText, setBottomText] = useState('');
  const [customMediaUrl, setCustomMediaUrl] = useState('https://media.giphy.com/media/LmNwrBhejkK9EFP504/giphy.gif');
  const [mediaType, setMediaType] = useState('image'); // 'image' or 'video'
  const [isGenerated, setIsGenerated] = useState(false);
  const memeRef = useRef(null);

  const determineMediaType = (url) => {
    // Simple check for common video extensions. This catches mp4, webm, ogg
    if (url.match(/\.(mp4|webm|ogg)$/i)) {
      setMediaType('video');
    } else {
      setMediaType('image'); // Covers static images and gifs
    }
  };

  const handleUrlChange = (e) => {
    const url = e.target.value;
    setCustomMediaUrl(url);
    determineMediaType(url);
    setIsGenerated(false); // Reset generation on URL change
  };


  const pickRandomMedia = () => {
    const randomIndex = Math.floor(Math.random() * dynamicMedia.length);
    const randomItem = dynamicMedia[randomIndex];
    setCustomMediaUrl(randomItem.url);
    setMediaType(randomItem.type);
    setIsGenerated(false);
  };

  const generateMemeFromText = () => {
    if (!customMediaUrl) {
      alert('Please select or enter a media URL first!');
      return;
    }

    if (!topText.trim() && !bottomText.trim()) {
      alert('Please enter some text for your meme!');
      return;
    }

    setIsGenerated(true);
  };

  const downloadMeme = () => {
    alert('Download functionality would require html2canvas or a backend processing step for rendering DOM over video elements!');
  };

  // Auto Meme Generator State
  const [autoMemeTop, setAutoMemeTop] = useState('');
  const [autoMemeBottom, setAutoMemeBottom] = useState('');
  const [autoMemeUrl, setAutoMemeUrl] = useState('');
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const autoMemeRef = useRef(null);

  const generateAutoMeme = () => {
    const randomGifIndex = Math.floor(Math.random() * brahmanandamGifs.length);
    const randomTextIndex = Math.floor(Math.random() * engineeringTexts.length);

    setAutoMemeUrl(brahmanandamGifs[randomGifIndex]);
    setAutoMemeTop(engineeringTexts[randomTextIndex].top);
    setAutoMemeBottom(engineeringTexts[randomTextIndex].bottom);
    setIsAutoGenerated(true);
  };

  return (
    <div className="meme-generator">
      <header className="header">
        <h1>Meme Generator</h1>
        <button className="logout-btn" onClick={() => window.location.reload()}>
          Logout
        </button>
      </header>

      <div className="generator-container">

        <div className="main-content">
          <div className="controls">
            <div className="text-inputs">
              <div className="input-group">
                <label htmlFor="mediaUrl">Custom Media URL (GIF, JPG, MP4)</label>
                <input
                  type="text"
                  id="mediaUrl"
                  value={customMediaUrl}
                  onChange={handleUrlChange}
                  placeholder="Paste any image or video URL here"
                />
              </div>

              <div className="input-group">
                <label htmlFor="topText">Top Text</label>
                <input
                  type="text"
                  id="topText"
                  value={topText}
                  onChange={(e) => setTopText(e.target.value)}
                  placeholder="Enter top text"
                />
              </div>

              <div className="input-group">
                <label htmlFor="bottomText">Bottom Text</label>
                <input
                  type="text"
                  id="bottomText"
                  value={bottomText}
                  onChange={(e) => setBottomText(e.target.value)}
                  placeholder="Enter bottom text"
                />
              </div>
            </div>

            <div className="action-buttons">
              <button onClick={pickRandomMedia} className="random-btn">
                🎲 Random Background
              </button>
              <button onClick={generateMemeFromText} className="generate-btn">
                Generate Meme
              </button>
              <button onClick={downloadMeme} className="download-btn">
                Download Meme
              </button>
            </div>
          </div>

          <div className="preview-section">
            <div className="meme-preview">
              {isGenerated ? (
                <div className="meme-dom-container" ref={memeRef}>
                  {topText && (
                    <div className="meme-text top-text">
                      {topText.toUpperCase()}
                    </div>
                  )}

                  {mediaType === 'video' ? (
                    <video
                      className="meme-media"
                      src={customMediaUrl}
                      autoPlay
                      loop
                      muted
                      playsInline
                    />
                  ) : (
                    <img className="meme-media" src={customMediaUrl} alt="Meme Background" />
                  )}

                  {bottomText && (
                    <div className="meme-text bottom-text">
                      {bottomText.toUpperCase()}
                    </div>
                  )}
                </div>
              ) : (
                <div className="placeholder">
                  <div className="placeholder-icon">🎥</div>
                  <p>Select a hilarious video or GIF, add text, and click Generate!</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Auto Meme Generator Section */}
      <div className="auto-generator-section">
        <h2>Meme Generator (Auto)</h2>
        <p>Click below to generate an automatic meme!</p>

        <button className="generate-btn auto-generate-btn" onClick={generateAutoMeme}>
          Generate Random Auto Meme
        </button>

        {isAutoGenerated && (
          <div className="preview-section auto-preview">
            <div className="meme-preview">
              <div className="meme-dom-container" ref={autoMemeRef}>
                {autoMemeTop && (
                  <div className="meme-text top-text">
                    {autoMemeTop}
                  </div>
                )}

                <img className="meme-media auto-media" src={autoMemeUrl} alt="Auto Meme GIF" />

                {autoMemeBottom && (
                  <div className="meme-text bottom-text">
                    {autoMemeBottom}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </div>

    </div>
  );
}

export default MemeGenerator;